### ISSUE TITLE
Pull theme images from archive

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox-Discord-Bot#18]
Find out how/where themes are stored, themes with image have ``hasImage`` property but does not have a direct link, requiring additional calls per command usage.

Additionally, decide what should be the first image, only one image is shown per embed on some platforms, music wheel is probably the most important image.

**Comment by JoseVarelaP** [comment]
Themes are stored at: `https://objects-us-east-1.dream.io/smthemes/[SMBuild Version]/[File]`
There is a special rule for themes that have multiple releases, where they are contained in a folder. These are already defined on the actual file directory itself in "Link" tags that are objects rather than strings.
In the case of the special rule, it becomes: `https://objects-us-east-1.dream.io/smthemes/[SMBuild Version]/Screenshots/[Theme KeyCode]/[File]`

Version with singular release: https://objects-us-east-1.dream.io/smthemes/StepMania%205/SIGMA%20-The%20Blue%20Dasher-%20v1.0.zip
Version with multiple releases: https://objects-us-east-1.dream.io/smthemes/StepMania%205/XX-starlight-/XX.-STARLiGHT-.twopointzero.v2.1.0HF.zip

For images, they're stored on: `https://objects-us-east-1.dream.io/smthemes/[SMBuild Version]/Screenshots/[Theme KeyCode]/screen[1-6].png`
Example: https://objects-us-east-1.dream.io/smthemes/StepMania%205/Screenshots/starlight/screen1.png

For the bot, only one should be shown, and it could be either the wheel or the gameplay screen.

**Comment by JoseVarelaP** [comment]
As for the `hasImage` property, there's actually a few themes that now have images but don't have the flag set, so I'll get to update those.

**Comment by moruzerinho6** [comment]
> For images, they're stored on: `https://objects-us-east-1.dream.io/smthemes/[SMBuild Version]/Screenshots/[Theme KeyCode]/screen[1-6].png`


Does ``SMBuild Version`` follow the same  naming scheme as used on theme page URL scheme? (eg. OITG, NITG, SM3.9_Plus) 

> For the bot, only one should be shown, and it could be either the wheel or the gameplay screen.

Thinking better, I could add a button named "Switch theme image", only one would still be shown at a time.

**Comment by JoseVarelaP** [comment]
> Does SMBuild Version follow the same naming scheme as used on theme page URL scheme? (eg. OITG, NITG, SM3.9-Plus)

Yes, it follows that one.

Also updated the json listing with the themes that currently have the images (https://github.com/JoseVarelaP/StepMania-Archive/commit/b5c5ddd6b8115eac38e34e447244bfbde2bc8ba0).

**Comment by moruzerinho6** [comment]
> For images, they're stored on: `https://objects-us-east-1.dream.io/smthemes/[SMBuild Version]/Screenshots/[Theme KeyCode]/screen[1-6].png` Example: https://objects-us-east-1.dream.io/smthemes/StepMania%205/Screenshots/starlight/screen1.png
> 
> For the bot, only one should be shown, and it could be either the wheel or the gameplay screen.

Small problem, image placement doesn't seem to follow a standard?

- Starlight Music wheel is [screen 3](https://objects-us-east-1.dream.io/smthemes/StepMania%205/Screenshots/starlight/screen3.png)
- Ultralight Music wheel is [screen 2](https://objects-us-east-1.dream.io/smthemes/StepMania%205/Screenshots/ultralight/screen2.png)

I could create a object for each theme poiting to the right index of the Music Wheel, but I want your confirmation first if that isn't a leftover bug or it is this way as intended.

**Comment by JoseVarelaP** [comment]
It's technically intended. It was never meant to follow a pattern, just 6 pictures that showcased the theme, generally being engine-controlled ones. However there's some other themes like [ITGMeat](https://objects-us-east-1.dream.io/smthemes/OITG/Screenshots/Meat/screen2.png), [Stepping Revision](https://objects-us-east-1.dream.io/smthemes/StepMania%205/Screenshots/StRev/screen5.png), SL, XIX, Starlight which contain special screens that are worth pointing out, which can eat a screen slot.

**Comment by moruzerinho6** [comment]
Done with https://github.com/TeamRizu/OutFox-Discord-Bot/commit/746f24f73666745b5104cafc0355127933f77b12
